### ISSUE TITLE
Postman export support

### ISSUE THREAD

**Issue by krolow** [matryer/silk#12]
Hey found silk quite interesting! I'm looking for to give a try in my next microservice project.

By the way while reading i was thinking in [postman](https://www.getpostman.com/) as far i know several people using for QA and test (not automated) purpose.

So i was think if make sense to add support for that in this project, if is that something that you are willing for to have into core, or might be some a part, a command that we run pointing the markdown that generates that?

I'm asking because i was thinking in give a try and implement that. :beers:

**Comment by matryer** [comment]
What would 'support' look like?

**Comment by krolow** [comment]
I was thinking to start some support only export the requests as one XML file to be imported in postman...

It would be some argument in command line like:

```
silk -silk.url="{endpoint}" {testfiles} --output-postman="{file-to-be-created}"
```

so it would run tests and generate one output as postman XML file to be imported in XML...

does that make any sense?

**Comment by matryer** [comment]
I'd prefer if this was an external tool (you are free to use the parse package from within silk to process the Silk files)?

**Comment by joyrexus** [comment]
Silk markdown descriptions seem similar to Blueprints (see #35).  If Silk descriptions can be converted into Blueprint-style descriptions, you could then easily convert them into [Postman collections](https://github.com/thecopy/apiary2postman) or [almost any other common API description format](https://apitransformer.com/#formats).

I think it's a little bit of a shame that Silk is introducing a slightly varying Markdown format for describing APIs, but perhaps there are some compelling reasons to do so?

**Comment by matryer** [comment]
Silk was designed without knowledge of Blueprint, and follows some core principals from the Go community around simplicity and the use of whitespace. Aside from that, it's pretty similar to Blueprint. I take the lead of where a project should go from the community of people who use it, so it's up to everyone what features we add etc. I'd say people should use Blueprint for now if they need all that extra tooling etc, Silk is designed to be _extremely_ simple.

Genuine question: If you want to convert Silk files to Blueprint, why are you using Silk and not Blueprint?

**Comment by matryer** [comment]
see conversation in https://github.com/matryer/silk/issues/35
