### ISSUE TITLE
Only show field types if the types are different

### ISSUE THREAD

**Issue by matryer** [matryer/silk#16]
To reduce noise, only show the field types if the fields are different.

**Comment by mattdotmatt** [comment]
Do you have an example of what this change would mean?

**Comment by matryer** [comment]
It says:

```
expected float64: 202  actual float64: 404
```

It would be enough to say:

```
expecte: 202  actual: 404
```

But keep the types if they are different:

```
expected string: 200  actual float64: 200
```

**Comment by narqo** [comment]
:+1: here! Current behaviour looks very annoying.
