### ISSUE TITLE
Support formatted JSON in response body assertions

### ISSUE THREAD

**Issue by narqo** [matryer/silk#24]
For a large bodies it'd be much user-friendlier to support formatted JSON in the body assert field. Currently if I have an assertion:

~~~
===

'''
{
  "resource": "api_status",
  "body": {
    "blah": "blah"
  }
}
'''
~~~

and my API returns `{"resource":"api_status","body":{"blah":"blah"}}`, I get "body doesn't match" error.

**Comment by matryer** [comment]
please see https://github.com/matryer/silk/issues/25
