### ISSUE TITLE
Request body isn't sent properly

### ISSUE THREAD

**Issue by craftgear** [matryer/silk#30]
When I send a request with a body option I can't receive form values on server side.

Request
```
## POST /api
* Content-type: "application/x-www-form-urlencoded"
{
  id: 1
}
===
* Status: 200
```

Server
```go
r.ParseForm()
fmt.Printf("%v", r.Form)
```
yields:
map[{  id: "1"}:[] ]

**Comment by matryer** [comment]
Technically, you're sending JSON but HTTP forms require an encoded string... Try:

    id=123

The thing is this gets ugly:

    a=1&b=2&c=3

Maybe Silk can provide a nicer way to do this? Perhaps similar to the URL parameter format but maybe it cares about the method?

**Comment by craftgear** [comment]
The workaround will do for me.

Thanks.
