### ISSUE TITLE
Blueprint compatible? Differences?

### ISSUE THREAD

**Issue by joyrexus** [matryer/silk#35]
Just curious to what extent silk's syntax and conventions are similar and/or compatible with [blueprint](https://apiblueprint.org)? I ask, because blueprint is a pretty established standard for documenting web APIs (along w/ Swagger and RAML, all of which are interconvertible) and there's already a lot of nice [tooling](https://apiblueprint.org/tools.html) around it (e.g., [`test2doc`](https://github.com/adams-sarah/test2doc)).

If different, is it possible to [convert](https://apitransformer.com) silk-based api docs into blueprints or other api-spec formats?

**Comment by matryer** [comment]
Silk was designed without knowledge of Blueprint, and follows some core principals from the Go community around simplicity and the use of whitespace. Aside from that, it's pretty similar to Blueprint. I take the lead of where a project should go from the community of people who use it, so it's up to everyone what features we add etc. I'd say people should use Blueprint for now if they need all that extra tooling etc, Silk is designed to be extremely simple.

Genuine question: If you want to convert Silk files to Blueprint, why are you using Silk and not Blueprint?

**Comment by joyrexus** [comment]
Appreciate the response.

>  If you want to convert Silk files to Blueprint, why are you using Silk and not Blueprint?

Good point.  Various colleagues of mine already use Blueprint and I originally found Silk by looking for Go based tooling for the spec. [Dredd](http://dredd.readthedocs.org/en/latest/) can be used for testing Blueprints in a similar manner and there's even [setup/teardown hooks for Go](http://dredd.readthedocs.org/en/latest/hooks-go/).  It's Node based, which is fine, but I always look for Go variants of python/ruby/node utilities because they're often simpler, faster, better engineered, and less dependency heavy. I'm more likely to contribute to Go-based projects and/or modify them for my own idiosyncratic needs.

Both Silk and Blueprint are Markdown-based conventions for describing web APIs ... very similar ways of describing the same thing.  So I guess my question was actually less about converting Silk Markdown descriptions to Blueprint Markdown descriptions than about the rationale for introducing a variant format. (You explained that.) 

Sort of wondering now if it would be terribly difficult to fork Silk and use it as a basis for parsing Blueprint docs ... but this is more off the cuff curiosity about the possibility than anything else.

**Comment by matryer** [comment]
I'd be interested to see any experiments in this area if it's something you want to pursue.
